--- 
title: "Teledetección con software Libre de código abierto"
author: "Hugo Añamuro y Antony Barja"
date: "`r Sys.Date()`"
bibliography:
- book.bib
- packages.bib
description: This is the training materials for the **R for Geospatial Processing**
  workshop at FOSS4G 2019, Bucarest (Romania).
documentclass: book
link-citations: yes
site: bookdown::bookdown_site
biblio-style: apalike
---

# Prerequisites

This workshop is designed for the attendance of FOSS4G 2019. So basics knowledge in GIS is expected (simple features, projections and CRS, geometrical operations, etc.).

No knowledge of R is required. A minimal knowledge of [(R)mardown](https://rmarkdown.rstudio.com/) will be a plus to take notes.

Please install R on your system and the following libraries.

Please follow installation instructions from the [CRAN projet](https://cran.r-project.org/).

The {sf} library needs several geospatial core libraries (GDAL, GEOS, PROJ) so please follow [{sf} installation instructions](https://github.com/r-spatial/sf/) to be sure to have those.

For Ubuntu users, ThinkR published a blogpost about [the installation of r 3 5 on Ubuntu 18.04 LTS and tips for spatial packages](https://rtask.thinkr.fr/installation-of-r-3-5-on-ubuntu-18-04-lts-and-tips-for-spatial-packages/)


For [OSGeoLive](https://live.osgeo.org) users, there is already some of them installed in the distribution.
Please start Jupyter Notebooks (Menu -> GeoSpatial -> Spatial Tools -> Jupyter Notebook). It should open a web page.

Click on `New` in the top right and start a new R Notebook. Then install only the following packages :



## About this document

This document had been written with the [R Bookdown package](https://bookdown.org/yihui/bookdown) and [Rstudio](https://www.rstudio.com). You can use the editor of your choice to follow the instruction, be careful on the path given by the {here} package.

To compile this example to PDF, you need XeLaTeX. You are recommended to install TinyTeX (which includes XeLaTeX): <https://yihui.name/tinytex/>.

You can contribute to this document on GitHub :

[https://github.com/Bakaniko/FOSS4G2019_Geoprocessing_with_R_workshop](https://github.com/Bakaniko/FOSS4G2019_Geoprocessing_with_R_workshop)



```{r include=FALSE}
# automatically create a bib database for R packages
knitr::write_bib(c(
  .packages(), 'bookdown', 'knitr', 'rmarkdown'
), 'packages.bib')
```

<!--chapter:end:index.Rmd-->

